name: Lint, Prettier and Build Checks

on:
  pull_request:
    branches: [main]

jobs:
  lint_prettier_build_checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Check Prettier
        run: yarn prettier-check

      - name: Check lint
        run: yarn lint

      - name: Build
        run: yarn build
